# プルリクエストにReviewersを追加するには true に設定します。
addReviewers: true

# プルリクエストにAssigneesを追加する場合は true に設定します。
addAssignees: true

# Reviewerに設定するメンバを追加します。
reviewers:
  - Younghan-J0
  - YoungHan-Jo
  - jo-younghan

# Reviewersに追加するメンバ数を指定できます。
# 追加メンバより設定数が少ない場合、ランダムで追加されます。
# 0に設定すると全てのReviewersのメンバが追加されます。
numberOfReviewers: 1

# Assigneesrに設定するメンバを追加します。
assignees:
  - Younghan-J0
  - YoungHan-Jo
  - jo-younghan

# Assigneessに追加するメンバ数を指定できます。
# 追加メンバより設定数が少ない場合、ランダムで追加されます。
# 0に設定すると全てのAssigneesのメンバが追加されます。
numberOfAssignees: 1
