# # Set to true to add reviewers to pull requests
# addReviewers: true

# # Set addAssignees to 'author' to set the PR creator as the assignee.
# addAssignees: true

# reviewers:
#   - Younghan-J0
#   - YoungHan-Jo
# # A number of reviewers added to the pull request
# # Set 0 to add all the reviewers (default: 0)
# numberOfReviewers: 1

# # # A list of reviewers to be added to pull requests (GitHub user name)
# # teamReviewers:
# #   - sre-team

# assignees:
#   - Younghan-J0
#   - YoungHan-Jo

# numberOfAssignees: 1

# プルリクエスト作成者は別途Assigneesに追加されるようになっています。

# プルリクエストにReviewersを追加するには true に設定します。
addReviewers: true

# プルリクエストにAssigneesを追加する場合は true に設定します。
addAssignees: true

# Reviewerに設定するメンバを追加します。
reviewers:
  - Younghan-J0
  - YoungHan-Jo
  - jo-younghan

# Reviewersに追加するメンバ数を指定できます。
# 追加メンバより設定数が少ない場合、ランダムで追加されます。
# 0に設定すると全てのReviewersのメンバが追加されます。
numberOfReviewers: 1

# Assigneesrに設定するメンバを追加します。
assignees:
  - Younghan-J0
  - YoungHan-Jo
  - jo-younghan

# Assigneessに追加するメンバ数を指定できます。
# 追加メンバより設定数が少ない場合、ランダムで追加されます。
# 0に設定すると全てのAssigneesのメンバが追加されます。
numberOfAssignees: 1
