name: Auto Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Define users
        id: define-users
        run: |
          touch auto_assign_users.txt
          echo "Younghan-J0" >> auto_assign_users.txt
          echo "YoungHan-Jo" >> auto_assign_users.txt
          echo "jo-younghan" >> auto_assign_users.txt

      - name: Debug users
        run: cat auto_assign_users.txt

      - name: Filter out the PR author
        id: filter-author
        run: |
          grep -v "^${{ github.actor }}$" auto_assign_users.txt > filtered_users.txt

      - name: Select a random user
        id: select-user
        run: echo "SELECTED_USER=$(shuf -n 1 filtered_users.txt)" >> $GITHUB_ENV

      - name: Debug selected user
        run: echo $SELECTED_USER

      - name: debug env user
        run: echo ${{ env.SELECTED_USER }}

      - name: Check if assignees exist
        id: check-assignees
        run: |
          ASSIGNEES=$(gh pr view ${{ github.event.pull_request.number }} --json assignees --jq '.assignees | length')
          echo "ASSIGNEES_COUNT=$ASSIGNEES" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add reviewer and assignee
        if: env.ASSIGNEES_COUNT == '0'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-reviewer $SELECTED_USER
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee $SELECTED_USER
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
