name: Auto Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Define users
        id: define-users
        run: |
          touch auto_assign_users.txt
          echo "Younghan-J0" >> auto_assign_users.txt
          echo "YoungHan-Jo" >> auto_assign_users.txt
          echo "jo-younghan" >> auto_assign_users.txt

      - name: Filter out the PR author
        id: filter-author
        run: |
          grep -v "^${{ github.actor }}$" auto_assign_users.txt > filtered_users.txt

      - name: Select a random user
        id: select-user
        run: echo "SELECTED_USER=$(shuf -n 1 filtered_users.txt)" >> "$GITHUB_OUTPUT"

      - name: Check if assignees exist
        id: check-assignees
        run: |
          ASSIGNEES=$(gh pr view ${{ github.event.pull_request.number }} --json assignees --jq '.assignees | length')
          echo "ASSIGNEES_COUNT=$ASSIGNEES" >> "$GITHUB_OUTPUT"

      - name: Check if labels exist
        id: check-labels
        run: |
          LABELS=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels | length')
          echo "LABELS_COUNT=$LABELS" >> "$GITHUB_OUTPUT"

      - name: Debug labels
        run: |
          echo "LABELS_COUNT: ${{ steps.check-labels.outputs.LABELS_COUNT }}"

      - name: Add reviewer and assignee
        if: ${{ steps.check-assignees.outputs.ASSIGNEES_COUNT == 0 && steps.check-labels.outputs.LABELS_COUNT == 0 }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-reviewer ${{ steps.select-user.outputs.SELECTED_USER }}
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee ${{ steps.select-user.outputs.SELECTED_USER }}
